name: Oskar Sharipov
description: Random blog
avatar: https://github.com/igoose1/igoose1.github.io/raw/master/images/logo.png

footer-links:
  email: oskar.sharipov@tuta.io
  github: igoose1/igoose1.github.io
  rss: rss
  stackoverflow: users/6760569/%d0%9e%d1%81%d0%ba%d0%b0%d1%80-%d0%a8%d0%b0%d1%80%d0%b8%d0%bf%d0%be%d0%b2

disqus: igoose
url: https://igoose.me
baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

